title: Heeju's portfolio
description: Java_Backend Developer
site_title: '임희주 | Java 백엔드 개발자'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: linxizhu1209
blog_url: https://blog.naver.com/dlahj1209
email: dlahj1209@naver.com
keybase_username: LimHeeJu
twitter_username: LimHeeJu
reddit_username: LimHeeJu

# absolute or relative
profile_picture: assets/images/희주프로필사진.png

# Google Analytics ID
google_analytics: 
